### ISSUE TITLE
Title and icon of the window unchanged

### ISSUE THREAD

**Issue by moritztim** [Oakchris1955/another-youtube-downloader#4]

**Comment by Oakchris1955** [comment]
@moritz-t-w ,provide more info

**Comment by moritz-t-w** [comment]
> @moritz-t-w ,provide more info

It says tk and has a frather symbol instead of "pornhub downloader" and a pic of your cat

**Comment by Oakchris1955** [comment]
@moritz-t-w ,you better not swear in public

**Comment by Oakchris1955** [comment]
@moritz-t-w ,imma take care of it in official release of Beta v2

**Comment by Oakchris1955** [comment]
![image](https://user-images.githubusercontent.com/80592203/163712609-2fe5fc45-7c11-4564-9fe9-e26bdff0498c.png)

Closing #4
