### ISSUE TITLE
Initial window complains about info not being available

### ISSUE THREAD

**Issue by moritztim** [Oakchris1955/another-youtube-downloader#5]
it Says `Audio info unavailable` `Audio info unavailable` and `Video info unavailable` `Video info unavailable` right when you open it for the first time

**Comment by Oakchris1955** [comment]
yeah, ik, all I want you to do now is find bugs

**Comment by Oakchris1955** [comment]
Reopening this and gonna change it

**Comment by Oakchris1955** [comment]
Changed it, reclosing it
